### PR TITLE
Added description and screenshot files

### PR DESCRIPTION
**Pull request by ExcaliburZero**
Added a description and screenshot file that will be used by the Mod tab of the main menu of Minetest.

### CODE REVIEW

**Comment by Kilarin** [comment]
Thank you very much!

**Comment by HybridDog** [comment]
l guess you can use a jpg screenshot and name it "screenshot.png" to reduce the file size.

**Comment by ExcaliburZero** [comment]
@HybridDog See: https://github.com/sofar/crops/pull/8#issuecomment-98484836

**Comment by HybridDog** [comment]
This screenshot is small, maybe it's better to use a png file with palette:
8.4kB
screenshot

**Pull request merged**
